
LIB_NAME = ce
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_OBJS = ce.o

#LIB_HEADERS = ce.h
INSTALL_HEADERS_DIR = libce   #include <libce/ce.h>

ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/compile.mk
include $(ARCO_MK)/install.mk
include $(ARCO_MK)/lib.mk
