

ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/compile.mk
include $(ARCO_MK)/install.mk

LIB_NAME = a
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_HEADERS = a.h
LIB_OBJS = a.o

INSTALL_HEADERS_DIR = liba

include $(ARCO_MK)/lib.mk


