
LIB_NAME = a
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_OBJS = a.o

#LIB_HEADERS = a.h
INSTALL_HEADERS_DIR = liba   #include <liba/a.h>

ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/compile.mk
include $(ARCO_MK)/install.mk
include $(ARCO_MK)/lib.mk


