

ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/build.mk
include $(ARCO_MK)/install.mk

LIB_NAME = a
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_HEADERS = a.h
LIB_OBJS = a.o

INSTALL_INCLUDEDIR = liba

include $(ARCO_MK)/lib.mk


