ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/compile.mk
include $(ARCO_MK)/install.mk

LIB_NAME = d
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_HEADERS = d.h
LIB_OBJS = d.o
INSTALL_HEADERS_DIR = libd
include $(ARCO_MK)/lib.mk
