ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/compile.mk
include $(ARCO_MK)/install.mk

LIB_NAME = ce
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_HEADERS = ce.h
LIB_OBJS = ce.o
INSTALL_HEADERS_DIR = libd
include $(ARCO_MK)/lib.mk
