usr/share/arco-tools/devel.sh
usr/share/arco-tools/flymake-c.mk
usr/share/arco-tools/install.mk
usr/share/arco-tools/build.mk
usr/share/arco-tools/subdirs.mk
usr/share/arco-tools/main.mk
usr/share/arco-tools/config.mk
usr/share/arco-tools/lib.mk
usr/share/arco-tools/bin.mk
usr/share/arco-tools/slice.mk
usr/share/arco-tools/emacs/
usr/share/emacs/site-lisp/yasnippet/snippets/text-mode/
usr/share/emacs/site-lisp/yasnippet/snippets/text-mode/python-mode/

