#!/bin/sh
# postrm script for arco-tools
#
# see: dh_installdeb(1)

set -e



case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
				texhash;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
