
CXXFLAGS = -I.
LDFLAGS  = -L.

LIB_NAME = a
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_OBJS = a.o

#LIB_HEADERS = a.h
INSTALL_HEADERS_DIR = liba   #include <liba/a.h>

include ../../../../make/default-flags.mk
include ../../../../make/library-rules.mk

