
LIB_NAME = b
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_OBJS = b.o

#LIB_HEADERS = b.h
INSTALL_HEADERS_DIR = libb   #include <libb/b.h>

include ../../../../make/install.mk
include ../../../../make/lib.mk

