
ARCO_MK ?= /usr/share/arco-tools
include $(ARCO_MK)/compile.mk
include $(ARCO_MK)/install.mk

LIB_NAME = b
LIB_VERSION = 2.3
LIB_SONAME  = 23
LIB_HEADERS = b.h
LIB_OBJS = b.o
INSTALL_HEADERS_DIR = libb

include $(ARCO_MK)/lib.mk
